### ISSUE TITLE
Binaries conflicting with existing commands creates error

### ISSUE THREAD

**Issue by SimenB** [lukechilds/zsh-nvm#12]
Such as greenkeeper, which has the short form `gk`, which on my machine is aliased (`gk: aliased to \gitk --all --branches`).

I then get a warning when nvm loads `gitk:unset:1: no such hash table element: gk`.

```sh-session
$ nvm ls
nvm:unset:1: no such hash table element: gk
       v0.10.47
       v0.12.16
->       v6.8.1
default -> 6 (-> v6.8.1)
node -> stable (-> v6.8.1) (default)
stable -> 6.8 (-> v6.8.1) (default)
iojs -> N/A (default)
lts/* -> lts/argon (-> N/A)
lts/argon -> v4.6.0 (-> N/A)
```

Worse is trying to use `gk` makes it loop infinitely.

```sh-session
$ gk enable
gitk:unset:1: no such hash table element: gk
gitk:unset:1: no such hash table element: greenkeeper
gitk:unset:1: no such hash table element: ncu
gitk:unset:1: no such hash table element: node
gitk:unset:1: no such hash table element: npm
gitk:unset:1: no such hash table element: npm-check-updates
gitk:unset:1: no such hash table element: typings
gitk:unset:1: no such hash table element: yarn
gitk:unset:1: no such hash table element: yarnpkg
gitk:unset:1: no such hash table element: gk
gitk:unset:1: no such hash table element: greenkeeper
gitk:unset:1: no such hash table element: ncu
gitk:unset:1: no such hash table element: node
gitk:unset:1: no such hash table element: npm
gitk:unset:1: no such hash table element: npm-check-updates
gitk:unset:1: no such hash table element: typings
gitk:unset:1: no such hash table element: yarn
gitk:unset:1: no such hash table element: yarnpkg
gitk:unset:1: no such hash table element: gk
gitk:unset:1: no such hash table element: greenkeeper
gitk:unset:1: no such hash table element: ncu
gitk:unset:1: no such hash table element: node
gitk:unset:1: no such hash table element: npm
gitk:unset:1: no such hash table element: npm-check-updates
gitk:unset:1: no such hash table element: typings
gitk:unset:1: no such hash table element: yarn
gitk:unset:1: no such hash table element: yarnpkg
gitk:unset:1: no such hash table element: gk
gitk:unset:1: no such hash table element: greenkeeper
gitk:unset:1: no such hash table element: ncu
gitk:unset:1: no such hash table element: node
gitk:unset:1: no such hash table element: npm
gitk:unset:1: no such hash table element: npm-check-updates
gitk:unset:1: no such hash table element: typings
gitk:unset:1: no such hash table element: yarn
gitk:unset:1: no such hash table element: yarnpkg
gitk:unset:1: no such hash table element: gk
gitk:unset:1: no such hash table element: greenkeeper
gitk:unset:1: no such hash table element: ncu
gitk:unset:1: no such hash table element: node
gitk:unset:1: no such hash table element: npm
gitk:unset:1: no such hash table element: npm-check-updates
gitk:unset:1: no such hash table element: typings
gitk:unset:1: no such hash table element: yarn
gitk:unset:1: no such hash table element: yarnpkg
```

etc.

This is using LAZY, tbw.

**Comment by lukechilds** [comment]
Hmmn, definitely an issue with lazy loading.

I'm pretty busy this weekend, I'm probably not going to get a chance to look at this until Monday. Disabling lazy loading should resolve the issue for now.

I'll let you know when it's sorted 👍

**Comment by lukechilds** [comment]
@SimenB Recreated this, working on a fix.

**Comment by lukechilds** [comment]
@SimenB Ok, I'm now checking if any commands exist globally before setting the lazy load functions. If they already exist, those commands are ignored. https://github.com/lukechilds/zsh-nvm/commit/4c6173938c2a1df130d0e98cd4a23d355ba0e0ab

Can you checkout the [fix-alias-bug](https://github.com/lukechilds/zsh-nvm/tree/fix-alias-bug) branch and let me know if that resolves the issue for you? If it does I'll merge into master.

**Comment by SimenB** [comment]
So `gk` won't work until nvm is loaded?

I'll test tonight

**Comment by lukechilds** [comment]
No `gk` won't work at all because the alias overrides it. That's how it would work without lazy loading.

**Comment by SimenB** [comment]
if nvm is loaded, then it works though. Why should lazy change that (other than the hit we get loading nvm the first time)?

**Comment by lukechilds** [comment]
Hmmn, it shouldn't do. The alias should be overwriting the function. That's how it's working on my dev VM.

If you disable lazy loading what happens when you run `gk`? Do you run `gitk` or Greenkeeper?

**Comment by SimenB** [comment]
@lukechilds OK, tested now, and you are correct! It's gitk which is run.

And your branch fixes the issue 😄

**Comment by lukechilds** [comment]
@SimenB Merged 👍
