### ISSUE TITLE
Add a lazy loader function for yarn if it's been installed via brew

### ISSUE THREAD

**Issue by lukechilds** [lukechilds/zsh-nvm#16]
As discussed in https://github.com/lukechilds/zsh-nvm/issues/15#issuecomment-267612088

**Comment by danez** [comment]
I have the same problem currently. I installed yarn via the installer and not via brew. And it would be nice if it would be lazy loaded.

If I do `type yarn` i see `yarn is /Users/username/.yarn/bin/yarn`. 

Anyway to figure out why it doesn't work?

Also I have other usecases for binaries that should init nvm. Maybe it would be nice to be able to specify commands that should be wrapped.

**Comment by lukechilds** [comment]
@danez Adding something like:

```shell
export NVM_LAZY_LOADERS="foo bar baz"
```

 should be fairly straight forward.

Can you explain your other use cases? Are you running scripts with `#!/usr/bin/env node` that aren't global modules?

**Comment by danez** [comment]
Exactly when I try to run eslint for example directly from the node_modules folder it prints a warning:
```
❯ node_modules/.bin/eslint src/
env: node: No such file or directory
```

**Comment by lukechilds** [comment]
`node node_modules/.bin/eslint src/` should work.

**Comment by danez** [comment]
👍
