### ISSUE TITLE
Antigen doesn't fully initialize

### ISSUE THREAD

**Issue by john-kurkowski** [lukechilds/zsh-nvm#19]
I ran `antigen update` recently. My themes stopped working. I bisected all my Antigen plugins. Everything works if I exclude zsh-nvm.

I did a `git bisect` on zsh-nvm, performing `antigen reset` in between checkouts. Looks like this started with 8bdba4f.

**Comment by lukechilds** [comment]
Sorry about that! Thanks for doing some digging.

So if you remove `return true` everything works ok?

Can you tell me your OS/zsh version and what `zsh-nvm` options (if any) you have enabled?

**Comment by lukechilds** [comment]
Would you mind trying this and seeing if it resolves your issue?

https://github.com/lukechilds/zsh-nvm/pull/20

**Comment by lukechilds** [comment]
@john-kurkowski actually, don't worry about that PR, it was a bug that needed fixing regardless of whether it was causing your problem so I've merged it into master.

Can you `antigen update` again and let me know if it's working?

**Comment by john-kurkowski** [comment]
No dice.

If I remove that line, `return 0`, it works again.

**Comment by john-kurkowski** [comment]
Versions/options:

macOS 10.12.1
antigen 1.3.2
zsh 5.3.1
```
export NVM_DIR=~/.nvm
export NVM_NO_USE=true
```

**Comment by lukechilds** [comment]
Hmmn, ok bare with me

**Comment by lukechilds** [comment]
Ok, appears to be an issue in a recent version of antigen. I just updated my antigen installation and I'm getting the same problem.

I think a plugin should be able to return so I'd consider this a bug in antigen not zsh-nvm. However I'll add a workaround for now so this doesn't affect any other antigen users and raise an issue with them.

**Comment by lukechilds** [comment]
@john-kurkowski It's working for me now, could you test again?

You may need to delete the `zsh-nvm` folder so antigen pulls down a fresh copy.

**Comment by john-kurkowski** [comment]
Works now! Thank you!

**Comment by lukechilds** [comment]
Thanks for your help on this @john-kurkowski 

Issue for antigen is here if you're interested: https://github.com/zsh-users/antigen/issues/386
