### ISSUE TITLE
Not compatible with npm plugin

### ISSUE THREAD

**Issue by adi1133** [lukechilds/zsh-nvm#23]
https://github.com/robbyrussell/oh-my-zsh/blob/3705d47bb3f3229234cba992320eadc97a221caf/plugins/npm/npm.plugin.zsh

**Comment by lukechilds** [comment]
Can you provide any more information?

**Comment by lukechilds** [comment]
I've just had a look, if the error you're getting is `permission denied: /npm_completion` then that's a bug in the npm plugin completely unrelated to `zsh-nvm`.

**Comment by lukechilds** [comment]
@adi1133 I've reported the npm plugin issue here: https://github.com/robbyrussell/oh-my-zsh/issues/5874

I'll close this now, if that wasn't the issue you were referring to feel free to re-open.
