### ISSUE TITLE
Auto load does not work when start ZSH inside a directory with .nvmrc

### ISSUE THREAD

**Issue by dlee** [lukechilds/zsh-nvm#28]
When I launch ZSH inside a directory with an `.nvmrc`, it fails to auto load the correct node version. I have to do a `cd .` in order for the auto load to trigger. It would be great if this use case was supported by `zsh-nvm`.

**Comment by lukechilds** [comment]
Hmmn, I assumed this worked already as I'm manually running `_zsh_nvm_auto_use` [on initial source](https://github.com/lukechilds/zsh-nvm/blob/4637e8f01bc8530af51ebdb1656363db75409643/zsh-nvm.plugin.zsh#L188) if it's enabled. It's possible `add-zsh-hook` returns a non zero exit code so it evaluates to false.

Thanks for taking the time to submit an issue, I'll take a look.

**Comment by lukechilds** [comment]
@dlee, this is already working for me, sounds like an issue with your environment.

What version of zsh are you using? Also, could you try running this and tell me what the output is?

```shell
add-zsh-hook chpwd _zsh_nvm_auto_use && echo yep || echo nope
```

**Comment by dlee** [comment]
Thanks for looking into it. Seems like it was indeed a clash with my environment. I was setting my path to:
```
PATH=~/bin:/usr/local/bin:/usr/local/sbin:$PATH
```
after loading `zsh-nvm`. When I moved that line to before loading the `zsh-nvm` plugin, it started working properly.
