### ISSUE TITLE
_zsh_nvm_global_binaries:1: no matches found: /Users/simen/.nvm/v0*/bin/*

### ISSUE THREAD

**Issue by SimenB** [lukechilds/zsh-nvm#3]
First of all, thanks for this!

Running master gives the error in the title, but using the commit before that (https://github.com/lukechilds/zsh-nvm/commit/1c6d8dd15ec0f177c56005033bfb77ecc6e28cea) works great.

If I get that error, it doesn't work, so it's not just noise.

This is having just node 6 installed.

**Comment by lukechilds** [comment]
Thanks for the detailed feedback, pretty sure I know what's causing it, I'll have a tinker and keep you posted 👍

**Comment by lukechilds** [comment]
I take it you have lazy loading enabled?

**Comment by SimenB** [comment]
Yup 😄

**Comment by lukechilds** [comment]
Sweet, if you turn off lady loading for now it should work, I'll get lazy loading fixed pronto though :)

**Comment by SimenB** [comment]
I'll just stay at https://github.com/lukechilds/zsh-nvm/commit/1c6d8dd15ec0f177c56005033bfb77ecc6e28cea, that works for now (WITH lazy loading).

**Comment by lukechilds** [comment]
Yeah, that version doesn't work with node versions <0.10. They are installed in a different path. I had updated the binary search to check both paths but zsh was complaining the the <v0.10 glob wasn't matching anything on your system as you didn't have any <0.10 versions installed.

I've Just applied nullglob to both the globs and now it should work fine if any of them don't match.

https://github.com/lukechilds/zsh-nvm/commit/870962197372ddc27360ac8e18446c2a098c969c

Can you try updating and let me know if it works for you?

**Comment by SimenB** [comment]
Yup, works great now. Thanks for the quick turnaround!
