### ISSUE TITLE
`node:unset:1: no such hash table element: yarn`

### ISSUE THREAD

**Issue by sodiumjoe** [lukechilds/zsh-nvm#31]
I've installed using the manual install method (I'm on current head of master) and yarn with `brew install yarn`.

`.zshrc`:
```zsh
export NVM_LAZY_LOAD=true
source ~/play/zsh-nvm/zsh-nvm.plugin.zsh
```

Everything works fine, but on each new shell, I get the following on the first invocation of node or any global module:

```zsh
node
node:unset:1: no such hash table element: yarn
>
```

**Comment by lukechilds** [comment]
Thanks for the bug report, will try and take a look later today.

**Comment by lukechilds** [comment]
Could you let me know you OS/zsh version?

**Comment by sodiumjoe** [comment]
Thanks for taking a look!

```bash
zsh --version
zsh 5.3.1 (x86_64-apple-darwin16.6.0)
```

macOS Sierra 10.12.5 (16F73)

**Comment by lukechilds** [comment]
Hmmn, I have the exact same zsh version and env var settings. I just installed yarn via brew and I'm not getting that issue.

I am on El Capitan not Sierra, but I doubt that would make a difference if the zsh versions are the same.

So you get that message on each new shell, not after running `node` or `yarn`?

**Comment by lukechilds** [comment]
Ooops, sorry just re-read your message, it's on the first invoc of node, I think I know what it might be.

**Comment by lukechilds** [comment]
Ok, I still can't recreate this issue but I'm pretty sure I know what could causing it.

Can you try checking out the `yarn-unset-notice` branch and let me know if that resolves the issue?

**Comment by sodiumjoe** [comment]
Fixed in that branch!

**Comment by lukechilds** [comment]
Great, I've merged that fix into master, thanks for catching that 👍

**Comment by learn2reid** [comment]
I'm having this issue now, 
`zstyle ':omz:plugins:nvm' lazy-cmd npmlist npl squoosh-cli sq prettier typescript yarn`
