### ISSUE TITLE
Lazy: Npm without other globals not available without loading nvm

### ISSUE THREAD

**Issue by SimenB** [lukechilds/zsh-nvm#4]
I _think_ this is the issue, not sure though...

I set this up on my work machine, and just `nvm install 6.4` gives the following from `which node` in a new shell:

```zsh
node () {
        unset -f node nvm
        _zsh_nvm_load
        node "$@"
}
```

Running `npm i -g npm` then a new session made no difference. I then installed `npm-check-update` and `typings`, which gave me:

```zsh
node () {
        unset -f ncu node npm npm-check-updates typings nvm
        _zsh_nvm_load
        node "$@"
}
```

`which npm` gave me `npm not found` up until the last one.

Not sure why, but maybe it'll give you a starting point for where to look 😄

**Comment by lukechilds** [comment]
Sorry a bit confused, when did you get `npm not found`, after you installed npm?

**Comment by lukechilds** [comment]
Ok, found the issue, for some insane reason `npm` gets ignored when `node` and `npm` are the only binaries. For example:

```shell
% ls $NVM_DIR/versions/*/*/bin/*(N)
/Users/lukechilds/.lazyload-test/versions/node/v6.4.0/bin/node
/Users/lukechilds/.lazyload-test/versions/node/v6.4.0/bin/npm

% ls $NVM_DIR/versions/*/*/bin/*(N) | xargs basename
node
```

But then if you install a module:

```shell
% ls $NVM_DIR/versions/*/*/bin/*(N)
/Users/lukechilds/.lazyload-test/versions/node/v6.4.0/bin/node
/Users/lukechilds/.lazyload-test/versions/node/v6.4.0/bin/npm
/Users/lukechilds/.lazyload-test/versions/node/v6.4.0/bin/package

% ls $NVM_DIR/versions/*/*/bin/*(N) | xargs basename
node
npm
package
```

Working on a fix...

**Comment by lukechilds** [comment]
Doh! Just needed to set `max-args` to 1 on `xargs`:

```shell
% ls $NVM_DIR/versions/*/*/bin/*(N)
/Users/lukechilds/.lazyload-test/versions/node/v6.4.0/bin/node
/Users/lukechilds/.lazyload-test/versions/node/v6.4.0/bin/npm

% ls $NVM_DIR/versions/*/*/bin/*(N) | xargs basename
node

% ls $NVM_DIR/versions/*/*/bin/*(N) | xargs -n1 basename
node
npm
```

Should be fixed as of https://github.com/lukechilds/zsh-nvm/commit/1be9149af66b7324adbfff0d43287f463009b194. `which npm` now works after a fresh install:

```shell
% which npm
npm () {
       	unset -f node npm nvm
       	_zsh_nvm_load
       	npm "$@"
}
```

**Comment by SimenB** [comment]
No problem, thanks for the quick fix!
