### ISSUE TITLE
NVM autocompletions

### ISSUE THREAD

**Issue by Glennmen** [lukechilds/zsh-nvm#57]
Would it be interesting to add autocompletion to zsh-nvm just like the default nvm plugin has? https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/nvm/_nvm

If interested I can try to make a PR for this.

**Comment by lukechilds** [comment]
A PR would be welcome for this :)

I will warn you though, my availability for OSS is not great right now so I can't promise I'll be able to review quickly.

**Comment by Glennmen** [comment]
@lukechilds I was thinking about copying it from the main `nvm` plugin so it should be a quick PR. Of course I will test it first before making a PR to be sure that it works with lazy loading.

**Comment by memark** [comment]
@lukechilds @Glennmen Could we as an easy start just activate the out-of-the-box completions already provided by _nvm-sh_? They are in
`https://github.com/nvm-sh/nvm/blob/master/bash_completion`
(and work with Zsh as well).

For example
`[[ -s $NVM_DIR/bash_completion ]] && \. $NVM_DIR/bash_completion`
could be added to
`zsh-nvm.plugin.zsh`
with or without a separate environment variable flag like `NVM_USE_COMPLETIONS`. (I would argue they could always be active.)

**Comment by lukechilds** [comment]
@memark this is a good suggestion and also solves the problem of our hardcoded completions coming out of sync with the installed nvm version which would be pretty frustrating for users.

(btw incase you weren't aware there is already a PR in progress here: https://github.com/lukechilds/zsh-nvm/pull/58)

**Comment by Glennmen** [comment]
@memark @lukechilds The reason why I don't like the included bash nvm-sh completion compared to the custom ZSH nvm completion.

bash nvm-sh completion:
![image](https://user-images.githubusercontent.com/11406433/77584145-9cc45c00-6ee2-11ea-8b2a-f6d099ce5752.png)

zsh nvm completion:
![image](https://user-images.githubusercontent.com/11406433/77584407-047aa700-6ee3-11ea-9318-b73c74b8d7dc.png)

Zsh completion gives the option to add extra information to the commands, which can of course be very useful when you are looking for the correct command.

**Comment by memark** [comment]
@Glennmen I totally understand. I guess it's a tradeoff between functionality and maintainability.
