### ISSUE TITLE
_zsh_nvm_lazy_load:3: bad pattern: global_binaries=(bower

### ISSUE THREAD

**Issue by yads** [lukechilds/zsh-nvm#6]
Seems to be an issue with the local array variables in my instance of oh-my-zsh on OSX. I fixed it by splitting declaration and assignment

```
local global_binaries
global_binaries=($(_zsh_nvm_global_binaries))
```

I can submit a PR for this, but I'm not sure if this is a localized issue.

**Comment by lukechilds** [comment]
Thanks for reporting this 👍 

What does `zsh --version` output for you?

**Comment by yads** [comment]
`zsh 5.0.8 (x86_64-apple-darwin15.0)`

**Comment by lukechilds** [comment]
Yeah seems like a zsh version issue, I just tried on my Mac's system zsh (5.0.8) and got the same error. On my newer brew version (5.2) it works fine. If you could submit a PR that would be brilliant!

Looks like it's time to set up unit tests... ;)

**Comment by lukechilds** [comment]
Resolved in https://github.com/lukechilds/zsh-nvm/pull/7
