### ISSUE TITLE
Add option to load nvm without loading node

### ISSUE THREAD

**Issue by lukechilds** [lukechilds/zsh-nvm#9]
There should be an option to load `nvm` but not load `node`. `nvm` already has this capability with `--no-use`. We should add an option to make use of this.

**Comment by lukechilds** [comment]
@maturano Are you able to check out the [`no-use`](https://github.com/lukechilds/zsh-nvm/tree/no-use branch) branch and let me know if those changes work for you.

You'll need to set the following option:

```shell
export NVM_NO_USE=true
```

By default it won't load node. You have to manually load node by using `nvm use`. For example:

```
$ node --version
zsh: command not found: node

$ nvm use 4
Now using node v4.2.1 (npm v2.14.7)

$ node --version
v4.2.1
```

**Comment by maturano** [comment]
@lukechilds I tested the `no-use` branch and everything work fine :+1:

**Comment by lukechilds** [comment]
@maturano Perfect, I'll merge into master tonight and update you when it's done.

**Comment by lukechilds** [comment]
Complete as of: https://github.com/lukechilds/zsh-nvm/commit/e2e47a8c212066f1e63fb785dd78fdc77652e211 https://github.com/lukechilds/zsh-nvm/commit/e379610cb929b635247280cb19e685af1c167c4d https://github.com/lukechilds/zsh-nvm/commit/6e2fc22ff37452a3b88232edf60e94ec8d85792a

@maturano It's in master now if you want to update, thanks for your help 👍
